### ISSUE TITLE
Fedora tests are "bad"

### ISSUE THREAD

**Issue by TJM** [jduncan-rva/newrhelic#13]
There is a syntax error:

```
  File "src/newrhelic.py", line 60
    if d_version = 'Fedora':    #we're using Fedora, psutil is a different here.
                 ^
SyntaxError: invalid syntax
```

(should be ==)

and then I got another error after fixing that about files not being scriptable. I think you meant to read the file into a string, then start split()'ing it?

**Comment by jduncan-rva** [comment]
jesus.

i need sleep.

On Thu, Jun 12, 2014 at 7:03 PM, Tommy McNeely notifications@github.com
wrote:

> There is a syntax error:
> 
>   File "src/newrhelic.py", line 60
>     if d_version = 'Fedora':    #we're using Fedora, psutil is a different here.
>                  ^
> SyntaxError: invalid syntax
> 
> (should be ==)
> 
> and then I got another error after fixing that about files not being
> scriptable. I think you meant to read the file into a string, then start
> split()'ing it?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jduncan-rva/newRHELic/issues/13.

## 

Thanks,

Jamie Duncan
@jamieeduncan
