### ISSUE TITLE
Config shouldn't define version, guid, etc

### ISSUE THREAD

**Issue by TJM** [jduncan-rva/newrhelic#17]
I don't think that the config file is the best place to define the following:

```
name = OS Statistics
guid = com.rhel.os_statistics
version = 0.1
```

The version and guid should be defined in the code for sure. I am not sure the name is used (I think that is configured in rpm.newrelic.com).

~tommy

**Comment by jduncan-rva** [comment]
you're right. it was just to get it up/running back when.

On Fri, Jun 13, 2014 at 12:15 PM, Tommy McNeely notifications@github.com
wrote:

> I don't think that the config file is the best place to define the
> following:
> 
> name = OS Statistics
> guid = com.rhel.os_statistics
> version = 0.1
> 
> The version and guid should be defined in the code for sure. I am not sure
> the name is used (I think that is configured in rpm.newrelic.com).
> 
> ~tommy
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jduncan-rva/newRHELic/issues/17.

## 

Thanks,

Jamie Duncan
@jamieeduncan
