### ISSUE TITLE
Issue while installing the rpm

### ISSUE THREAD

**Issue by SushilRangari** [jduncan-rva/newrhelic#2]
Hi ,

I have tried to install the newRHELic plugin , but it giving me error, 

Traceback (most recent call last):
  File "/usr/bin/newrhelic", line 32, in ?
    from daemon import runner
  File "/usr/lib64/python2.4/site-packages/daemon/**init**.py", line 42
    from . import version
         ^
SyntaxError: invalid syntax

Can you please help me here

**Comment by jduncan-rva** [comment]
Hmmm.... that's a new one. 
The daemon module is upstream in pypi, etc. I've included it here to make life easier for the original customer this was made for.

What version of RHEL/Python are you using? This was designed only for RHEL 6.

Thanks,

Jamie

**Comment by SushilRangari** [comment]
Hi Jamie,

My server is having Red Hat Enterprise Linux Server release 5.8 and python version is Python 2.4.3 (by default)  but on my system i have other version of python as well

[root@server]# ls -l /usr/bin/python*
-rwxr-xr-x 2 root root 8304 Oct 23  2012 /usr/bin/python
lrwxrwxrwx 1 root root    6 Feb 15  2013 /usr/bin/python2 -> python
-rwxr-xr-x 2 root root 8304 Oct 23  2012 /usr/bin/python2.4
-rwxr-xr-x 2 root root 8328 Nov  7  2012 /usr/bin/python26
-rwxr-xr-x 2 root root 8328 Nov  7  2012 /usr/bin/python2.6
-rwxr-xr-x 1 root root 8344 Nov 11 11:48 /usr/bin/python2.7

Please suggest.

Thanks
Sushil R

**Comment by jduncan-rva** [comment]
Sushil,

Right now the RPM installs the libraries into the default Python's path (python 2.4 in RHEL 5.x). It SHOULD work if you move the libraries around / buiild it from source on a system, but it's untested on RHEL 5. That may well be coming down the road if there is desire.

Thanks,

Jamie Duncan

**Comment by SushilRangari** [comment]
thanks Jamie for replying. I will try to build a rpm from source, and will share with you if face any thing related to it
