### ISSUE TITLE
Build newRHELic for RHEL 5.x

### ISSUE THREAD

**Issue by jduncan-rva** [jduncan-rva/newrhelic#3]

**Comment by bgarlock** [comment]
Hi!  Is this available for 5.x yet?  Many thanks,

Bruce

**Comment by jduncan-rva** [comment]
Apologies this reply took so long. 
I am marking out time in the next 7-10 days to work through a handful of issues for this and I will run a build against RHEL 5 as well. I'll add that RPM to a new release then.

**Comment by jduncan-rva** [comment]
My lab is finally back up! I'm actually upgrading my home Satellite server, after upgrading my home RHEV instance. So I have a RHEL 5 build system again.

**Comment by TJM** [comment]
For what its worth, we use mock to build el5 RPMs when we need them. We do have ovirt and satellite running in our lab too tho, for testing the RPMs before deploying them to the _few_ straggling servers still on 5. Now that the "cleanup" has happened, maybe this can be noarch, which would help too.

**Comment by jduncan-rva** [comment]
it's looking like noarch will work (i've been running test builds on
Fedora's koji platform on and off all morning).

But it looks like EL5 isn't going to be able to happen without a lot of the
hacking I ripped out last night. EL5 doesn't have python-psutil, and it
looks like it won't build on py 2.4.

Will likely take the hours to configure upstart and get it submitted to
Fedora and into EPEL 7 instead.

On Thu, Jun 12, 2014 at 12:18 PM, Tommy McNeely notifications@github.com
wrote:

> For what its worth, we use mock to build el5 RPMs when we need them. We do
> have ovirt and satellite running in our lab too tho, for testing the RPMs
> before deploying them to the _few_ straggling servers still on 5. Now
> that the "cleanup" has happened, maybe this can be noarch, which would help
> too.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jduncan-rva/newRHELic/issues/3#issuecomment-45913694.

## 

Thanks,

Jamie Duncan
@jamieeduncan

**Comment by TJM** [comment]
Yea, I have been wanting to play with koji, but barely understand mock. I actually created my first RPM from scratch a couple weeks ago :) ... previously we had just been rebuilding srpms or applying updates (such as VMWare ESXi 5.5 SDK).

Dealing with the old base packages can be a pain. I note that python26 and python26-psutil are in EPEL 5, but no python26-daemon, so you would have to publish both packages _ugh_

Looking forward to seeing newrhelic in EPEL **6** too if you can.

~tommy

**Comment by jduncan-rva** [comment]
If you want to see a failed RHEL 5 build to help troubleshoot:
My Steps:

```
$ python setup.py sdist;cp dist/newrhelic-0.1.tar.gz ~/rpmbuild/SOURCES/;rpmbuild -bs newrhelic.spec
$ koji build --scratch el5-candidate ~/rpmbuild/SRPMS/newrhelic-0.1-13.fc20.src.rpm
```

Sample results are at 
http://koji.fedoraproject.org/koji/taskinfo?taskID=7040369

For now I'm going to close this. Feel free to re-open if you can come up with a way to make it work in RHEL 5.

**Comment by jduncan-rva** [comment]
I should be submitting it this afternoon for Package Review.

On Thu, Jun 12, 2014 at 12:43 PM, Tommy McNeely notifications@github.com
wrote:

> Yea, I have been wanting to play with koji, but barely understand mock. I
> actually created my first RPM from scratch a couple weeks ago :) ...
> previously we had just been rebuilding srpms or applying updates (such as
> VMWare ESXi 5.5 SDK).
> 
> Dealing with the old base packages can be a pain. I note that python26 and
> python26-psutil are in EPEL 5, but no python26-daemon, so you would have to
> publish both packages _ugh_
> 
> Looking forward to seeing newrhelic in EPEL (6) too if you can.
> 
> ~tommy
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jduncan-rva/newRHELic/issues/3#issuecomment-45916784.

## 

Thanks,

Jamie Duncan
@jamieeduncan

**Comment by TJM** [comment]
I have it building and running on RHEL5, except it doesn't work via daemon.

https://github.com/TJM/newRHELic/commit/92ea8d3eb070da75a31fc0e00f835f44a180c257

 I require python26-psutils and python-daemon (there is no python26-daemon). I need to know if it is safe to include the python 2.4 version of daemon (somehow) or maybe we can get them to release python26-daemon ?

**Comment by TJM** [comment]
I have it working with daemon now.

**Comment by TJM** [comment]
I have a "test" version for RHEL5/CentOS5 that I installed to some of our legacy servers, and it seems to work fine. I am focused on getting the NFS stats going... hopefully before the next release, but if you would like a "test" version, let me know.

**Comment by jduncan-rva** [comment]
@TJM  how did the RHEL 5 version come out?

**Comment by jduncan-rva** [comment]
closing this for now. if @TJM wants to run with a RHEL5-specific package that'd be awesome.

**Comment by TJM** [comment]
@jduncan-rva - I am continuing to release a CentOS5/RHEL5(?) version of https://github.com/LarkIT/newrelic-nfsiostat (which I spawned off from here). There was a little bit of trickery in the spec file to make it work, but its really not too bad. Not that I am trying to take clients from you, but if they are solely interested in the NFS stats portion, they can try out my package to see if it works for them. :)
