### ISSUE TITLE
Proxy support doesn't appear to work?

### ISSUE THREAD

**Issue by TJM** [jduncan-rva/newrhelic#4]
I am seeing direct connection attempts even with enable_proxy = True.

```
[root@sf-devbatch-01 inc]# host platform-api.newrelic.com
platform-api.newrelic.com has address 50.31.164.164
[root@sf-devbatch-01 inc]# May 28 23:59:37 sf-devbatch-01 kernel: Firewall: *TCP_OUT Blocked* IN= OUT=eth0 SRC=10.0.0.156 DST=50.31.164.164 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=45934 DF PROTO=TCP SPT=46352 DPT=443 WINDOW=14600 RES=0x00 SYN URGP=0 UID=0 GID=0 
May 28 23:59:38 sf-devbatch-01 kernel: Firewall: *TCP_OUT Blocked* IN= OUT=eth0 SRC=10.0.0.156 DST=50.31.164.164 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=45935 DF PROTO=TCP SPT=46352 DPT=443 WINDOW=14600 RES=0x00 SYN URGP=0 UID=0 GID=0 
May 28 23:59:40 sf-devbatch-01 kernel: Firewall: *TCP_OUT Blocked* IN= OUT=eth0 SRC=10.0.0.156 DST=50.31.164.164 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=45936 DF PROTO=TCP SPT=46352 DPT=443 WINDOW=14600 RES=0x00 SYN URGP=0 UID=0 GID=0 
```

**Comment by jduncan-rva** [comment]
Hi TJM,

The proxy code is pretty simple. 

this is from NewRHELic.**init**():

```
            if self.enable_proxy:
                self.proxy_type = config.get('proxy','proxy_type')
                self.http_proxy = config.get('proxy','httpproxy_url')
                self.http_proxy_port = config.get('proxy','httpproxy_port')
```

and this is from NewRHELic.add_to_new_relic():

```
if self.enable_proxy:
                proxy_handler = urllib2.ProxyHandler({'%s' % self.proxy_type : '%s:%s' % (self.http_proxy, self.http_proxy_port)})
                opener = urllib2.build_opener(proxy_handler)
            else:
                opener = urllib2.build_opener(urllib2.HTTPHandler(), urllib2.HTTPSHandler())
```

So I'm just using the urllib2 ProxyHandler object. It's documented here:
https://docs.python.org/2/library/urllib2.html#urllib2.ProxyHandler

If you know of a better way to implement it / why it's not working on your firewall, i'lm happy to make any needed changes. 

Thanks,

Jamie Duncan

**Comment by TJM** [comment]
OK, so the argument to ProxyHandler needs to be a dict that maps protocols to proxy servers. So something like:

``` python
proxy_handler = urllib2.ProxyHandler({
    'http': '%s:%s' % (self.http_proxy, self.http_proxy_port)},
    'https': '%s:%s' % (self.http_proxy, self.http_proxy_port)}
})
```

I think that "proxy_type" might be a misinterpreted. I assumed that was to select the "type" of proxy server, as in SOCKS5 or HTTP. Since the default value was "http" it seemed logical, but the way it is used in the code indicates something else, like it is the protocol that would be used. I don't know if there would ever be any "http://" requests, but it might be a good idea to handle that differently. 

~tommy

**Comment by TJM** [comment]
Did you take this off the NewRelic plugin board? I was going to create a JIRA ticket to install it now that I figured the proxies out, and couldn't find it.

**Comment by jduncan-rva** [comment]
http://newrelic.com/plugins/red-hat-global-support-services/154

On Fri, Jun 6, 2014 at 11:58 AM, Tommy McNeely notifications@github.com
wrote:

> Did you take this off the NewRelic plugin board? I was going to create a
> JIRA ticket to install it now that I figured the proxies out, and couldn't
> find it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jduncan-rva/newRHELic/issues/4#issuecomment-45353219.

## 

Thanks,

Jamie Duncan
@jamieeduncan

**Comment by TJM** [comment]
Sorry for going off topic... :)

So the proxy does work if I set  `proxy_type = https`, but I think that is a bit confusing. I will try to fork and come up with a proposed solution.

**Comment by jduncan-rva** [comment]
looking forward to the pull request.

**Comment by TJM** [comment]
Closing. This was fixed in https://github.com/jduncan-rva/newRHELic/pull/8
