### ISSUE TITLE
NFS Stats do not show up properly in NewRelic

### ISSUE THREAD

**Issue by TJM** [jduncan-rva/newrhelic#5]
I put the NewRHELic plugin into debug mode, and verified that the NFS metrics are being reported, but they do not appear as a "tab" in NewRelic. I see "Overview", "CPU", "Disk", "Memory" and "Network" ... all of which are more or less in the "Servers" (newrelic-sysmond) graphs. I do see the raw metrics in the NewRelic interface if I click on the server name in the top left (to the left of the "Overview" tab)... and in that raw metrics screen, I can click a metric to get a graph for that one metric, but I was hoping that there would be a "NFS" tab, then under than graphs per mounted filesystem.

Here is some re-formatted information that I gleamed from the debug output:

```
[snip]
        "Component/NFS/home/username/Metrics/rpcbklog[int]":0.0,
        "Component/NFS/home/username/Time/Write/RTT/avg[ms]":1.002,
        "Component/NFS/home/username/Write/writes[sec]":0.021999999999999999,
        "Component/NFS/home/username/Write/kb[sec]":0.107,
        "Component/NFS/home/username/Read/ops[kb]":98.549000000000007,
        "Component/NFS/home/username/Write/retrans[int]":0,
        "Component/NFS/home/username/Metrics/ops[sec]":16.66,
        "Component/NFS/home/username/Time/Read/RTT/avg[ms]":8.6010000000000009,
        "Component/NFS/home/username/Time/Read/Execute Time/avg[ms]":9.2469999999999999,
        "Component/NFS/home/username/Read/retrans[int]":0,
        "Component/NFS/home/username/Write/ops[kb]":4.8949999999999996,
        "Component/NFS/home/username/Time/Write/Execute Time/avg[ms]":2.5049999999999999,
        "Component/NFS/home/username/Read/ops[sec]":0.023,
        "Component/NFS/home/username/Read/kb[sec]":2.2599999999999998,
[snip]
```

Potential Issues:
- ~~I wonder if we should somehow replace the "/" in the filesystem name so that there aren't so many slashes? (although I tried mounting /test, and I don't see it either) Alternatively, maybe we could prefix them with \ like `\/home\/username` to get it to treat that as a single entity?~~
- The [units](https://docs.newrelic.com/docs/plugin-developer-resources/metric-units-reference) seem wrong on several of these... For example:
  - `.../Read/kb[sec]` should be `..../Read[kb/sec]`

I realize this may end up being a NewRelic issue, but just wanted to take a look at the actual data before going to them. ;)

~tommy

**Comment by TJM** [comment]
Apparently the "tabs" are called "Dashboards" and they are created by the plugin author. So, once we get the metric names/units straight, it would be worth checking that out.

https://docs.newrelic.com/docs/plugin-dev/working-with-plugin-dashboards

**Comment by TJM** [comment]
Another issue is the "precision" of the data. Apparently something is happening to the string values when they get converted to floats? Maybe we should round those to 2 decimal places or something?

**Comment by jduncan-rva** [comment]
TJM,
The NFS stats were the initial reason I started then, and then the initial customer ended up not using them, so they've sorta' just atrophied.

The Dashboard issue is a limitation of New Relic, and makes me think NFS stats might be a standalone plugin. What do you think?

**Comment by TJM** [comment]
I agree.. and I have massively re-written the NFS portion of your plugin...
nfsiostat is python as well, so I have gotten into it directly. I worked on
it pretty much all day today and have it working the way I wanted, but
still no graphs of course.

The next thing on my list is to "aggregate" the stats in some meaningful
way (that I have not yet defined) ;)

I was going to ask you if you had any objections to me just keeping the NFS
stuff separate. Sounds like that is amicable. I will let you know when I
have something ready for review.

**Comment by jduncan-rva** [comment]
Tommy,

That sounds awesome. Looking forward to seeing it.
Thanks for contributing.

-jduncan

**Comment by TJM** [comment]
Let me know what you think.  https://github.com/TJM/newRHELic/tree/nfsiostat

I have not done much testing other than my "dev" server, and it appears to be working, so far ;)

**Comment by TJM** [comment]
Some background info...

The first iteration of "nfsiostat" (iostat) are cumulative stats since the filesystem was mounted. If you run them with an argument such as "10" they update every 10 seconds and the numbers they display represent the last 10 seconds. We don't really want the initial line, as it is basically trash, we really want it to run with "60" as the argument so that we get data over the last 60 seconds. I thought about managing a nfsiostat "process" and trying to parse the output, but as I started looking into it, I found out that nfsiostat is python as well. So, I copied /usr/sbin/nfsiostat to (./src/)nfsiostat.py (so I could "include" it). I then had to add the `if __name__ == "__main__"` part so that it wouldn't try to "run" when I imported it. It wasn't really designed to be used as a module. :)

I am only using a couple functions and the `DeviceData` class from it. I just basically looked at what they would do if they ran every 60 seconds, and put that into the `_update_nfs_stats` method. I also had to separate the "calculations" from the "display" (good programming practice anyhow) in the DeviceData class. 

I don't know what the "license" implications are, or whether we should be packaging this into a folder where its newrhelic.nfsiostat or something? (just blundering through right now)

~tommy

**Comment by jduncan-rva** [comment]
Instead of pulling in a copy of nfsiostat, can you make it a build dependency and just import the DeviceData that you're using?

**Comment by TJM** [comment]
Maybe? I don't really understand python all that well, I googled my way through the stuff yesterday. Since it doesn't have a ".py" on the end of it, I am not sure how to "import" it. Also, being in /usr/sbin made it difficult :)... I welcome suggestions :)

Besides I had to make changes, since nfsiostat was not originally written to be used as a module... I thought about submitting those changes to the nfsiostat project, but getting that pulled all the way back to RHEL/CentOS is not likely, so I took the easy way out.

An alternative might be to just copy the (2?) necessary functions and class directly into the newrelic.py, and trim DeviceData down to just what we need. I was not really sure what the best practice is there ;)

**Comment by jduncan-rva** [comment]
Where did you find python source for nfsiostat?

On Thu, Jun 12, 2014 at 12:52 PM, Tommy McNeely notifications@github.com
wrote:

> Maybe? I don't really understand python all that well, I googled my way
> through the stuff yesterday. Since it doesn't have a ".py" on the end of
> it, I am not sure how to "import" it. I welcome suggestions :)
> 
> Besides I had to make changes, since nfsiostat was not originally written
> to be used as a module... I thought about submitting those changes to the
> nfsiostat project, but getting that pulled all the way back to RHEL/CentOS
> is not likely, so I took the easy way out.
> 
> An alternative might be to just copy the (2?) necessary functions and
> class directly into the newrelic.py, and trim DeviceData down to just what
> we need. I was not really sure what the best practice is there ;)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jduncan-rva/newRHELic/issues/5#issuecomment-45917896.

## 

Thanks,

Jamie Duncan
@jamieeduncan

**Comment by jduncan-rva** [comment]
are you looking at https://github.com/pjunod/nfsiostat/blob/master/nfsiostat
?

On Thu, Jun 12, 2014 at 1:00 PM, Jamie Duncan jamie.e.duncan@gmail.com
wrote:

> Where did you find python source for nfsiostat?
> 
> On Thu, Jun 12, 2014 at 12:52 PM, Tommy McNeely notifications@github.com
> wrote:
> 
> > Maybe? I don't really understand python all that well, I googled my way
> > through the stuff yesterday. Since it doesn't have a ".py" on the end of
> > it, I am not sure how to "import" it. I welcome suggestions :)
> > 
> > Besides I had to make changes, since nfsiostat was not originally written
> > to be used as a module... I thought about submitting those changes to the
> > nfsiostat project, but getting that pulled all the way back to RHEL/CentOS
> > is not likely, so I took the easy way out.
> > 
> > An alternative might be to just copy the (2?) necessary functions and
> > class directly into the newrelic.py, and trim DeviceData down to just what
> > we need. I was not really sure what the best practice is there ;)
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/jduncan-rva/newRHELic/issues/5#issuecomment-45917896
> > .
> 
> ## 
> 
> Thanks,
> 
> Jamie Duncan
> @jamieeduncan

## 

Thanks,

Jamie Duncan
@jamieeduncan

**Comment by TJM** [comment]
I copied it from /usr/sbin/nfsiostat.

nfs-utils-1.2.3-39.el6.x86_64

It probably makes sense to get it "from the horses mouth" if we are going to "include" it?

**Comment by jduncan-rva** [comment]
the link i sent was a fork to tweak the output formatting.
this would solve your import question:
http://stackoverflow.com/questions/2601047/import-a-python-module-without-the-py-extension

I can't believe nfsiostat isn't a wrapper for a proper module. That makes
me sad. At any rate, we could make nfs-utils a dependency and import what
we need that way. Let me know what you think.

On Thu, Jun 12, 2014 at 1:04 PM, Tommy McNeely notifications@github.com
wrote:

> I copied it from /usr/sbin/nfsiostat.
> 
> It probably makes sense to get it "from the horses mouth" if we are going
> to "include" it?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jduncan-rva/newRHELic/issues/5#issuecomment-45919491.

## 

Thanks,

Jamie Duncan
@jamieeduncan

**Comment by TJM** [comment]
I am thinking this is where we need to decide whether we want to "split" the NFS portion off. I think, given the volume of data NFS produces vs everything else, it make sense. There is also really nothing "RHEL" specific about the NFS stats. Someone should be able to take the NFS code and package it for their specific Linux and it should work. (anything Linux 2.6.18(?)+) 

Even the pfjunod version doesn't have the `if __name__ == "__main__"` ... stuff, which means you can't import it, even if the solution above does work. It would probably require a re-jiggering of nfsiostat to make it a module/wrapper to make it so that we can import it... and getting those packages back into RHEL/CentOS on my whim is not likely ;)

In the new code, since we aren't using nfsiostat directly, rather some "copied" form of it, we don't need it anymore, but the previous package should have it as a dependency.
