### ISSUE TITLE
newrhelic-plugin stop exits with Bad file descriptor

### ISSUE THREAD

**Issue by TJM** [jduncan-rva/newrhelic#6]
It does "stop" properly, but gives an ugly looking backtrace...

```
# /etc/init.d/newrhelic-plugin stop
Terminating on signal 15
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib64/python2.6/logging/__init__.py", line 1517, in shutdown
[root@sf-devstore-01 ~]#     h.close()
  File "/usr/lib64/python2.6/logging/__init__.py", line 836, in close
    self.stream.close()
IOError: [Errno 9] Bad file descriptor
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib64/python2.6/logging/__init__.py", line 1517, in shutdown
    h.close()
  File "/usr/lib64/python2.6/logging/__init__.py", line 836, in close
    self.stream.close()
IOError: [Errno 9] Bad file descriptor
```

**Comment by jduncan-rva** [comment]
that's a new one... will investigate.
my personal lab was down for a few weeks, and is back up and I have cycles again to work on this and some other projects.

The initial customer needed something that had no dependencies, so I cooked a bunch of stuff into the RPM that shouldn't have been there. You'll notice that has been cleaned out, the structure is much more sane and the spec file is more developed. I'll be submitting it to Fedora/EPEL soon and maybe into RHEL after that.

**Comment by TJM** [comment]
For what its worth, we are running on a fairly minimal CentOS 6 box, but I don't think that is the problem. I presume it has something to do with logging based on the backtrace, which needs work anyhow (creating files with reliable names in /tmp is a security issue). The logfile and loglevel should probably be "configurable" items too.

**Comment by jduncan-rva** [comment]
agreed. The original use case was way out of line with anything considered good practice. A lot of this cruft stemmed from the need to fit that environment. And why I'm keen to clean it up now.

**Comment by TJM** [comment]
Perhaps another clue... I spun a new RPM locally with the latest changes, and found that I get the IO error every time a log message emits, but only when running through daemon. When I run it directly in python interactive, it works fine.

```
DEBUG    newrhelic:_get_nfs_stats: processing NFS volume - /www/store.cache
Traceback (most recent call last):
  File "/usr/lib64/python2.6/logging/__init__.py", line 800, in emit
    self.flush()
  File "/usr/lib64/python2.6/logging/__init__.py", line 762, in flush
    self.stream.flush()
IOError: [Errno 9] Bad file descriptor

```

**Comment by jduncan-rva** [comment]
going to dig into this one shortly.  cleaning up the spec file / setup.py
to handle multiple arches right now.

On Thu, Jun 12, 2014 at 7:24 PM, Tommy McNeely notifications@github.com
wrote:

> Perhaps another clue... I spun a new RPM locally with the latest changes,
> and found that I get the IO error every time a log message emits, but only
> when running through daemon. When I run it directly in python interactive,
> it works fine.
> 
> DEBUG    newrhelic:_get_nfs_stats: processing NFS volume - /www/store.cache
> Traceback (most recent call last):
>   File "/usr/lib64/python2.6/logging/__init__.py", line 800, in emit
>     self.flush()
>   File "/usr/lib64/python2.6/logging/**init**.py", line 762, in flush
>     self.stream.flush()
> IOError: [Errno 9] Bad file descriptor
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jduncan-rva/newRHELic/issues/6#issuecomment-45960230.

## 

Thanks,

Jamie Duncan
@jamieeduncan

**Comment by TJM** [comment]
I had to clean up a lot of that to get it to build/install and actually run on EL5 and 6, so it may be done :)

**Comment by TJM** [comment]
http://stackoverflow.com/questions/14758299/python-logging-daemon-destroys-file-handle?rq=1

Looks like daemon purposely closes all file handles (useful!?), unless we preserve them.

... as a followup to that, it doesn't look like "daemon.runner" is going to work for us because it sets up its own "DaemonContext" in an effort to try to "simplify" the process I am guessing. It looks like the path to resolution here is to setup our own "runner.py" with something like the following in self.daemon_context:

```
   self.daemon_context.file_preserve = self.data.logger.handlers
```

That's just a swag ;)

**Comment by TJM** [comment]
Solved.
